# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 19:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SourceSentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='parallelsentence',
            name='document',
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(help_text='The name of the Document', max_length=200),
        ),
        migrations.AlterField(
            model_name='document',
            name='task',
            field=models.ForeignKey(help_text='The Task that this Document belongs to', on_delete=django.db.models.deletion.CASCADE, to='qe.Task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(help_text='A short description of the Task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(help_text='The name of the Task', max_length=200),
        ),
        migrations.DeleteModel(
            name='ParallelSentence',
        ),
        migrations.AddField(
            model_name='sourcesentence',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qe.Document'),
        ),
        migrations.AddField(
            model_name='referencetranslation',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qe.SourceSentence'),
        ),
        migrations.AddField(
            model_name='machinetranslation',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qe.SourceSentence'),
        ),
    ]
