# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qe', '0002_auto_20170704_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the machine translation system', max_length=200)),
                ('type', models.CharField(choices=[('1', 'phrase-based SMT'), ('2', 'hierarchical SMT'), ('3', 'factored SMT'), ('4', 'rule-based'), ('5', 'template-based'), ('6', 'neural MT'), ('7', 'other')], help_text='The type of machine translation technology \n        that this system employs', max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='referencetranslation',
            name='translator',
            field=models.CharField(blank=True, help_text='The name or id of the translator \n        that produced this reference', max_length=200),
        ),
        migrations.AlterField(
            model_name='qemodel',
            name='type',
            field=models.CharField(choices=[('1', 'continuous'), ('2', 'binary'), ('3', 'ranking')], help_text='The type of Quality Estimation tasks \n        that this model is capable of', max_length=1),
        ),
    ]
