# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qe', '0003_auto_20170704_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinetranslation',
            name='system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qe.System'),
        ),
    ]
