# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 20:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qe', '0004_machinetranslation_system'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SourceSentence',
            new_name='ParallelSentence',
        ),
        migrations.RenameField(
            model_name='machinetranslation',
            old_name='target',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='referencetranslation',
            old_name='target',
            new_name='text',
        ),
    ]
