# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 21:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qe', '0006_auto_20170705_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='referencefile',
            field=models.FileField(blank=True, null=True, upload_to='dataset/references'),
        ),
        migrations.AddField(
            model_name='document',
            name='sourcefile',
            field=models.FileField(blank=True, null=True, upload_to='dataset/sources'),
        ),
        migrations.AddField(
            model_name='document',
            name='targetfile',
            field=models.FileField(blank=True, null=True, upload_to='dataset/target'),
        ),
        migrations.AlterField(
            model_name='machinetranslation',
            name='system',
            field=models.ForeignKey(blank=True, help_text='The machine translation system  \n        that produced this sentence', null=True, on_delete=django.db.models.deletion.CASCADE, to='qe.System'),
        ),
        migrations.AlterField(
            model_name='parallelsentence',
            name='document',
            field=models.ForeignKey(help_text='The document that this sentence belongs to', on_delete=django.db.models.deletion.CASCADE, to='qe.Document'),
        ),
        migrations.AlterField(
            model_name='qemodel',
            name='model',
            field=models.FileField(upload_to='models'),
        ),
    ]
