# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qe', '0007_auto_20170706_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='referencefile',
            field=models.FileField(blank=True, null=True, upload_to='files/dataset/references'),
        ),
        migrations.AlterField(
            model_name='document',
            name='sourcefile',
            field=models.FileField(blank=True, null=True, upload_to='files/dataset/sources'),
        ),
        migrations.AlterField(
            model_name='document',
            name='targetfile',
            field=models.FileField(blank=True, null=True, upload_to='files/dataset/target'),
        ),
    ]
