# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qe', '0008_auto_20170706_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qemodel',
            name='model',
            field=models.FileField(upload_to='files/models'),
        ),
    ]
