# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qe', '0009_auto_20170706_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='imported',
            field=models.BooleanField(default=False),
        ),
    ]
