# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qe', '0010_document_imported'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MachineTranslationEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('evaluation', models.ForeignKey(help_text='The evaluation set that this evaluation belongs to', on_delete=django.db.models.deletion.CASCADE, to='qe.DocumentEvaluation')),
                ('translation', models.ForeignKey(help_text='The MT output that this evaluation refers to', on_delete=django.db.models.deletion.CASCADE, to='qe.MachineTranslation')),
            ],
        ),
        migrations.CreateModel(
            name='MachineTranslationFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('targetfile', models.FileField(upload_to='files/dataset/target')),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceTranslationFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencefile', models.FileField(upload_to='')),
            ],
        ),
        migrations.RenameModel(
            old_name='ParallelSentence',
            new_name='Sentence',
        ),
        migrations.AlterField(
            model_name='document',
            name='imported',
            field=models.BooleanField(default=False, help_text='Specifies if the sentences have been imported from the files'),
        ),
        migrations.AlterField(
            model_name='document',
            name='referencefile',
            field=models.FileField(blank=True, help_text='Optional text file with one reference translation \n        per line, following the order of the source sentences in the \n        source file', null=True, upload_to='files/dataset/references'),
        ),
        migrations.AlterField(
            model_name='document',
            name='sourcefile',
            field=models.FileField(blank=True, help_text='Text file with one source sentence per line', null=True, upload_to='files/dataset/sources'),
        ),
        migrations.AlterField(
            model_name='document',
            name='targetfile',
            field=models.FileField(blank=True, help_text='Text file with one machine translation output per line,\n        following the order of the source sentences in the source file', null=True, upload_to='files/dataset/target'),
        ),
        migrations.AddField(
            model_name='referencetranslationfile',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qe.Document'),
        ),
        migrations.AddField(
            model_name='machinetranslationfile',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qe.Document'),
        ),
        migrations.AddField(
            model_name='machinetranslationfile',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qe.System'),
        ),
        migrations.AddField(
            model_name='documentevaluation',
            name='document',
            field=models.ForeignKey(help_text='The document which is being evaluated', on_delete=django.db.models.deletion.CASCADE, to='qe.Document'),
        ),
        migrations.AddField(
            model_name='documentevaluation',
            name='model',
            field=models.ForeignKey(help_text='The model to be applied for the evaluation ', on_delete=django.db.models.deletion.CASCADE, to='qe.QEModel'),
        ),
    ]
