# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qe', '0011_auto_20170707_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='evaluated',
            field=models.BooleanField(default=False, help_text='Specifies if all sentences have been evaluated'),
        ),
        migrations.AlterField(
            model_name='document',
            name='imported',
            field=models.BooleanField(default=False, help_text='Specifies if all sentences have been imported from the files'),
        ),
    ]
