# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qe', '0012_auto_20170707_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='sourcefile',
            field=models.FileField(help_text='Text file with one source sentence per line', upload_to='files/dataset/sources'),
        ),
        migrations.AlterField(
            model_name='document',
            name='targetfile',
            field=models.FileField(help_text='Text file with one machine translation output per line,\n        following the order of the source sentences in the source file', upload_to='files/dataset/target'),
        ),
        migrations.AlterField(
            model_name='documentevaluation',
            name='document',
            field=models.ForeignKey(blank=True, help_text='The document which is being evaluated', null=True, on_delete=django.db.models.deletion.CASCADE, to='qe.Document'),
        ),
    ]
