# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 16:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qe', '0013_auto_20170707_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentevaluation',
            name='document',
            field=models.ForeignKey(help_text='The document which is being evaluated', on_delete=django.db.models.deletion.CASCADE, to='qe.Document'),
        ),
        migrations.AlterField(
            model_name='documentevaluation',
            name='model',
            field=models.ForeignKey(blank=True, help_text='The model to be applied for the evaluation ', null=True, on_delete=django.db.models.deletion.CASCADE, to='qe.QEModel'),
        ),
    ]
